@startuml
start
:начало;
:расчет цены за прием;
:ввод;
:вывод цены за услугу;
:рассмотр другого предложени, следовательно -> скидки (пенсионерам, льготникам), предложение на запись с более низкой ценой (зависит от определенных условий);
if (цена устраивает?) then (да)
  if (онлайн?) then (да)
    :переход на сайт с оплатой онлайн;
  else (нет)
    :оплата очно;
  endif
  :услуга оплачена;
  stop
else (нет)
  :рассмотр другого предложения, следовательно -> скидки (пенсионерам, льготникам), предложение на запись с более низкой ценой (зависит от определенных условий);
  detach
endif
@enduml
