@startuml
start 
:начало;
:нужно записаться на прием;
:ввод (к какому врачу);
:ввод (на какую дату и время);
:запись на другое время (дата, число);

if (запись доступна?) then (да)
  if (онлайн?) then (да)
    :переход на сайт с записью онлайн;
  else (нет)
    :запись через поликлинику;
  endif
  :пациент записан;
  stop
else (нет)
  : запись на другое время (дата, число);
  detach
endif
@enduml
